name: Auth Service CD

on:
  repository_dispatch:
    types: [deploy-auth-service]
  workflow_dispatch:
    inputs:
      version:
        description: 'Auth service version to deploy'
        required: true
        default: 'latest'

env:
  AWS_REGION: us-east-1
  SERVICE_NAME: auth-service

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout current repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Parse deployment information
      id: deployment
      run: |
        echo "🎯 Auth Service CD Pipeline Started"
        
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          VERSION="${{ github.event.inputs.version }}"
          COMMIT_SHA="${{ github.sha }}"
          echo "📋 Manual deployment triggered"
        else
          VERSION="${{ github.event.client_payload.version }}"
          COMMIT_SHA="${{ github.event.client_payload.commit_sha }}"
          echo "🤖 Automatic deployment from CI"
        fi
        
        if [ -z "$VERSION" ]; then
          echo "❌ No version specified"
          exit 1
        fi
        
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "commit_sha=$COMMIT_SHA" >> $GITHUB_OUTPUT
        
        echo "📦 Deploying Auth Service version: $VERSION"
        echo "🔗 From commit: $COMMIT_SHA"

    - name: Verify ECR image exists
      run: |
        VERSION="${{ steps.deployment.outputs.version }}"
        
        echo "🔍 Verifying Auth Service image exists in ECR..."
        aws ecr-public describe-images \
          --repository-name "cj-auth-svc" \
          --image-ids imageTag="$VERSION" \
          --region us-east-1 || {
          echo "❌ Auth Service image $VERSION not found in ECR"
          exit 1
        }
        echo "✅ Auth Service image $VERSION found in ECR"

    - name: Clone cjet-k8s repository
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository_owner }}/cjet-k8s-public
        token: ${{ secrets.K8S_REPO_TOKEN }}
        path: cjet-k8s-public
        ref: main

    - name: Update Auth Service in Helm values
      run: |
        cd cjet-k8s-public/helm
        VERSION="${{ steps.deployment.outputs.version }}"
        
        echo "📝 Current Helm values (auth section):"
        grep -A10 "^  auth:" values.yaml || echo "Auth section not found"
        
        # Update only the auth service tag
        sed -i '/^  auth:/,/^  [a-zA-Z]/ { 
          /tag:/ {
            s/tag: .*/tag: '$VERSION'/
          }
        }' values.yaml
        
        echo ""
        echo "✅ Updated auth service to version: $VERSION"
        echo "📝 Updated Helm values (auth section):"
        grep -A10 "^  auth:" values.yaml

    - name: Commit and push Auth Service update
      run: |
        cd cjet-k8s-public
        VERSION="${{ steps.deployment.outputs.version }}"
        COMMIT_SHA="${{ steps.deployment.outputs.commit_sha }}"
        
        # Git configuration
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action - Auth Service CD"
        
        # Check for changes
        if git diff --quiet; then
          echo "ℹ️ No changes to commit"
          exit 0
        fi
        
        # Commit changes
        git add helm/values.yaml
        git commit -m "🚀 Update auth-service to $VERSION

        🔧 Service: auth-service
        📦 Version: $VERSION
        🔗 Commit: $COMMIT_SHA
        ⚡ Updated by Auth Service CD pipeline

        🤖 Generated with GitHub Actions"
        
        # Push changes with retry logic
        for attempt in {1..3}; do
          echo "🚀 Push attempt $attempt"
          if git push origin main; then
            echo "✅ Push successful"
            break
          fi

          echo "❌ Push failed, fetching latest changes..."
          git fetch origin main

          # Fast-forward merge (safe, no conflicts possible)
          if git merge --ff-only origin/main; then
            echo "🔄 Fast-forward successful"
          else
            echo "💥 Cannot fast-forward - manual resolution required"
            exit 1
          fi

          if [ $attempt -eq 3 ]; then
            echo "❌ Maximum retry attempts reached"
            exit 1
          fi

          # Random delay to avoid simultaneous retries
          sleep $((RANDOM % 10 + 5))
        done
        
        echo "✅ Auth Service deployment committed and pushed"
        echo "🎉 ArgoCD will automatically sync the changes"

    - name: Deployment summary
      run: |
        VERSION="${{ steps.deployment.outputs.version }}"
        
        echo "🎉 Auth Service CD completed successfully!"
        echo ""
        echo "📋 Deployment Summary:"
        echo "  🔧 Service: auth-service"
        echo "  📦 Version: $VERSION"
        echo "  🎯 Target: Kubernetes cluster"
        echo "  📝 Updated: cjet-k8s/helm/values.yaml"
        echo ""
        echo "⏳ Next steps:"
        echo "  1. ArgoCD will detect the changes automatically"
        echo "  2. Auth service will be deployed with rolling update"
        echo "  3. Monitor the deployment in ArgoCD dashboard"
        echo ""
        echo "🔗 ArgoCD will deploy to:"
        echo "  • Namespace: user"
        echo "  • Service: auth-service"
        echo "  • Image: public.ecr.aws/v3g6g4v7/cj-auth-svc:$VERSION"